[package]
name = "finalProject"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html





[dependencies]
csv="*"
rand="*"
rand_distr="*"
dot = "0.1.4"
petgraph = "0.6.4"