[package]
name = "finalProject"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv="*"
rand="*"
rand_distr="*"
ndarray = "0.15.0"
ndarray-rand = "0.14.0"
mnist = "0.6.0"
num = "0.4.1"